version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - $PWD:/app
  nginx:
    image: nginx:stable
    ports:
      - 8000:80
    volumes:
      - $PWD:/usr/share/nginx/html
