-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Multiplication.GamePage exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


yourAnswer : Translations -> String
yourAnswer translations =
    t translations "multiplication.gamePage.yourAnswer"


correctAnswer : Translations -> String
correctAnswer translations =
    t translations "multiplication.gamePage.correctAnswer"


enterHint : Translations -> String
enterHint translations =
    t translations "multiplication.gamePage.enterHint"


arrowsHint : Translations -> String
arrowsHint translations =
    t translations "multiplication.gamePage.arrowsHint"


operation : Translations -> String -> String -> String
operation translations num total =
    tr translations Curly "multiplication.gamePage.operation" [ ( "num", num ), ( "total", total ) ]


retriesLeft : Translations -> String -> String
retriesLeft translations n =
    tr translations Curly "multiplication.gamePage.retriesLeft" [ ( "n", n ) ]


check : Translations -> String
check translations =
    t translations "multiplication.gamePage.check"


skip : Translations -> String
skip translations =
    t translations "multiplication.gamePage.skip"
