-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Multiplication.GameFinishedPage exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


header : Translations -> String
header translations =
    t translations "multiplication.gameFinishedPage.header"


numRange : Translations -> String
numRange translations =
    t translations "multiplication.gameFinishedPage.numRange"


numRangeDesc : Translations -> String -> String -> String
numRangeDesc translations from to =
    tr translations Curly "multiplication.gameFinishedPage.numRangeDesc" [ ( "from", from ), ( "to", to ) ]


operationsNum : Translations -> String
operationsNum translations =
    t translations "multiplication.gameFinishedPage.operationsNum"


correctAnswersNum : Translations -> String
correctAnswersNum translations =
    t translations "multiplication.gameFinishedPage.correctAnswersNum"


wrongAnswersNum : Translations -> String
wrongAnswersNum translations =
    t translations "multiplication.gameFinishedPage.wrongAnswersNum"


retriesNum : Translations -> String
retriesNum translations =
    t translations "multiplication.gameFinishedPage.retriesNum"


totalTime : Translations -> String
totalTime translations =
    t translations "multiplication.gameFinishedPage.totalTime"


detailedChecking : Translations -> String
detailedChecking translations =
    t translations "multiplication.gameFinishedPage.detailedChecking"


yes : Translations -> String
yes translations =
    t translations "multiplication.gameFinishedPage.yes"


no : Translations -> String
no translations =
    t translations "multiplication.gameFinishedPage.no"


newGame : Translations -> String
newGame translations =
    t translations "multiplication.gameFinishedPage.newGame"


seeAnswers : Translations -> String
seeAnswers translations =
    t translations "multiplication.gameFinishedPage.seeAnswers"
