-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Multiplication.SettingsPage exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


header : Translations -> String
header translations =
    t translations "multiplication.settingsPage.header"


minNumOfDigits : Translations -> String
minNumOfDigits translations =
    t translations "multiplication.settingsPage.minNumOfDigits"


minNumOfDigitsDesc : Translations -> String -> String
minNumOfDigitsDesc translations n =
    tr translations Curly "multiplication.settingsPage.minNumOfDigitsDesc" [ ( "n", n ) ]


maxNumOfDigits : Translations -> String
maxNumOfDigits translations =
    t translations "multiplication.settingsPage.maxNumOfDigits"


maxNumOfDigitsDesc : Translations -> String -> String
maxNumOfDigitsDesc translations n =
    tr translations Curly "multiplication.settingsPage.maxNumOfDigitsDesc" [ ( "n", n ) ]


maxNumOfRetries : Translations -> String
maxNumOfRetries translations =
    t translations "multiplication.settingsPage.maxNumOfRetries"


maxNumOfRetriesDesc : Translations -> String
maxNumOfRetriesDesc translations =
    t translations "multiplication.settingsPage.maxNumOfRetriesDesc"


operationsNum : Translations -> String
operationsNum translations =
    t translations "multiplication.settingsPage.operationsNum"


operationsNumDesc : Translations -> String
operationsNumDesc translations =
    t translations "multiplication.settingsPage.operationsNumDesc"


detailedChecking : Translations -> String
detailedChecking translations =
    t translations "multiplication.settingsPage.detailedChecking"


detailedCheckingDesc : Translations -> String
detailedCheckingDesc translations =
    t translations "multiplication.settingsPage.detailedCheckingDesc"


start : Translations -> String
start translations =
    t translations "multiplication.settingsPage.start"
